name: Build and Publish

on:
  workflow_dispatch:

env:
  CURSEFORGE_PROJID: 336554
  JAVE_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Get Info and Perform Substitutions
      run: |
        # Parse fabric/gradle.properties into key-value pairs
        function parse_gradle_props() {
          RETURNVAL=$(grep -v '^\s*#' $1 | sed -e 's/^[ \t]*//;s/[ \t]*$//' | sed -e 's/[ \t]*=[ \t]*/=/' | grep -E -v '^[^=]*\.[^=]*=')
          echo "$RETURNVAL"
        }
        GRADLE_PROPS=$(parse_gradle_props common.properties)
        GRADLE_PROPS+=$(parse_gradle_props fabric/gradle.properties)
        GRADLE_PROPS+=$(parse_gradle_props forge/gradle.properties)
        GRADLE_PROPS+=$(parse_gradle_props neoforge/gradle.properties)

        # Parse each line of the key-value pairs
        VAR_NAMES=()
        echo "Add the following to the environmental variables of this step:"
        while IFS= read -r line; do
          # Skip empty lines
          [[ "$line" == "" ]] && continue

          key=$(echo "$line" | cut -d= -f1)
          value=$(echo "$line" | cut -d= -f2-)

          VAR_NAMES+=("$key")
          export "$key"="$value"
          echo "$key"="$value"
        done <<< "$GRADLE_PROPS"

        # Generate dynamic strings based on the build configuration
        function set_action_env() {
          echo "$1"="$2" >> $GITHUB_ENV
        }

        set_action_env "MC_VERSION_RANGE" "[${minecraft_version_min}, ${minecraft_version_max})"
        set_action_env "GITHUB_RELEASE_TITLE" "${mod_version} for Minecraft ${minecraft_version} (Forge, Neoforge and Fabric)"
        set_action_env "GITHUB_TAG_NAME" "${mod_version}_${minecraft_version}"
        set_action_env "CURSEFORGE_FORGE" "${minecraft_version}-${mod_version}-forge"
        set_action_env "CURSEFORGE_FABRIC" "${minecraft_version}-${mod_version}-fabric"
        set_action_env "CURSEFORGE_FABRICAPI" "306612@${fabric_version}(required)"
        set_action_env "CURSEFORGE_NEOFORGE" "${minecraft_version}-${mod_version}-neoforge"
        set_action_env "CURSEFORGE_CLOTHCONFIG" "348521@${cloth_config_version}(required)"
        set_action_env "CURSEFORGE_FABRICSHIELDLIB" "380649@${fabric_shield_lib_version}(required)"
        set_action_env "CURSEFORGE_MODMENU" "308702@${mod_menu_version}(optional)"

        # Perform substitutions on the change log
        GRADLE_PROPS_KEYS=$(echo ${VAR_NAMES[@]})
        bash -c "source .github/substitution.sh && perform_variable_substitution $GRADLE_PROPS_KEYS < CHANGELOG.txt" > CHANGELOG

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVE_VERSION }}
        distribution: 'temurin'

    - name: Make Gradle Wrapper Executable
      if: ${{ runner.os != 'Windows' }}
      run: |
        chmod +x ./forge/gradlew
        chmod +x ./neoforge/gradlew
        chmod +x ./fabric/gradlew

    - name: Build Forge
      run: cd forge && ./gradlew clean build && cd ..

    - name: Build Neoforge
      run: cd neoforge && ./gradlew clean build && cd ..

    - name: Build Fabric
      run: cd fabric && ./gradlew clean build && cd ..

    - name: Publish to GitHub
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        name: ${{ env.GITHUB_RELEASE_TITLE }}
        changelog-file: CHANGELOG

        # Only include this section if you wish to publish your assets on GitHub.
        github-tag: ${{ env.GITHUB_TAG_NAME }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-draft: true

        files: |
          forge/build/libs/!(*-@(dev|sources|javadoc)).jar
          neoforge/build/libs/!(*-@(dev|sources|javadoc)).jar
          fabric/build/libs/!(*-@(dev|sources|javadoc)).jar

    - name: Publish to CurseForge (Fabric version)
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        changelog-file: CHANGELOG
        # Only include this section if you wish to publish your assets on CurseForge.
        curseforge-id: $${{ env.CURSEFORGE_PROJID }}
        curseforge-token: "${{ secrets.CURSEFORGE_TOKEN }}"

        name: ${{ env.CURSEFORGE_FABRIC }}
        loaders: fabric
        version-type: release
        files: fabric/build/libs/!(*-@(dev|sources|javadoc)).jar
        java: Java ${{ env.JAVE_VERSION }}
        game-versions: ${{ env.MC_VERSION_RANGE }}
        curseforge-dependencies: |
          ${{ env.CURSEFORGE_FABRICAPI }},
          ${{ env.CURSEFORGE_CLOTHCONFIG }},
          ${{ env.CURSEFORGE_FABRICSHIELDLIB }},
          ${{ env.CURSEFORGE_MODMENU }},

    - name: Publish to CurseForge (Neoforge version)
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        changelog-file: CHANGELOG
        # Only include this section if you wish to publish your assets on CurseForge.
        curseforge-id: $${{ env.CURSEFORGE_PROJID }}
        curseforge-token: "${{ secrets.CURSEFORGE_TOKEN }}"

        name: ${{ env.CURSEFORGE_NEOFORGE }}
        loaders: neoforge
        version-type: beta
        files: neoforge/build/libs/!(*-@(dev|sources|javadoc)).jar
        java: Java ${{ env.JAVE_VERSION }}
        game-versions: ${{ env.MC_VERSION_RANGE }}
        curseforge-dependencies: |
          ${{ env.CURSEFORGE_CLOTHCONFIG }}

    - name: Publish to CurseForge (Forge version)
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        changelog-file: CHANGELOG
        # Only include this section if you wish to publish your assets on CurseForge.
        curseforge-id: $${{ env.CURSEFORGE_PROJID }}
        curseforge-token: "${{ secrets.CURSEFORGE_TOKEN }}"

        name: ${{ env.CURSEFORGE_FORGE }}
        loaders: forge
        version-type: beta
        files: forge/build/libs/!(*-@(dev|sources|javadoc)).jar
        java: Java ${{ env.JAVE_VERSION }}
        game-versions: ${{ env.MC_VERSION_RANGE }}
        curseforge-dependencies: |
          ${{ env.CURSEFORGE_CLOTHCONFIG }}
