name: Build and Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        submodules: true

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Make Gradle Wrapper Executable
      if: ${{ runner.os != 'Windows' }}
      run: chmod +x ./forge/gradlew && chmod +x ./fabric/gradlew

    - name: Build Forge
      run: cd forge && ./gradlew clean build && cd ..

    - name: Build Fabric
      run: cd fabric && ./gradlew clean build && cd ..

    - name: Publish (CurseForge/Modrinth/GitHub)
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        # Only include this section if you wish to publish your assets on CurseForge.
        curseforge-id: 336554
        curseforge-token: "${{ secrets.CURSEFORGE_TOKEN }}"

        # Only include this section if you wish to publish your assets on GitHub.
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-draft: true
        changelog-file: CHANGELOG.txt

        files: |
          forge/build/libs/!(*-@(dev|sources|javadoc)).jar
          forge/build/libs/*-@(dev|sources|javadoc).jar
          fabric/build/libs/!(*-@(dev|sources|javadoc)).jar
          fabric/build/libs/*-@(dev|sources|javadoc).jar
